// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b392827b-b7c3-47bc-9d9c-40ab75b6fb9b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onColorChange();
void onModeChange();
void onNightModeChange();
void onCloudSerialChange();

CloudColoredLight color;
int mode;
CloudSchedule nightMode;
String cloudSerial;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cloudSerial, READWRITE, ON_CHANGE, onCloudSerialChange);
  ArduinoCloud.addProperty(color, READWRITE, ON_CHANGE, onColorChange);
  ArduinoCloud.addProperty(mode, READWRITE, ON_CHANGE, onModeChange);
  ArduinoCloud.addProperty(nightMode, READWRITE, ON_CHANGE, onNightModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
